name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/segment-display/segment-display
          npm install
          npm run build
          cd dist
          tar -zcf segment-display.tgz *

      # Upload build file to the releas as an asset.
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/segment-display/segment-display/dist/segment-display.tgz
          asset_name: segment-display.tgz
          tag: ${{ github.ref }}
          overwrite: true
